### PR TITLE
make libvirt::network::bridge param optional

### PR DESCRIPTION
**Pull request by maxenced**
There is no need to force bridge parameter. Template was already correct with https://github.com/cirrax/puppet-libvirt/blob/master/templates/network.xml.erb#L12 conditional, but manifest was still requiring the bridge parameter.

### CODE REVIEW

**Comment by trefzer** [comment]
do we not need to say <% if @bridge!= '' -%> in the template ? (I did not try !)

**Comment by maxenced** [comment]
You're right !

**Comment by maxenced** [comment]
here we go

**Comment by trefzer** [comment]
Merged in v2.1.0
but github cannot find ;( so closing manually.
Thanks for the contribution.

**Pull request closed without merging**
