### PR TITLE
Add support for Ubuntu 22.04 LTS (Jammy Jellyfish) and update Ubuntu operatingsystem_support

### PR DESCRIPTION
**Pull request by raoulbhatia**
This required to introduce 2 new hiera data files for Ubuntu 18.04 LTS and 20.04.LTS 
as `qemu-kvm` is a virtual package since Ubuntu 21.10.

See https://packages.ubuntu.com/search?keywords=qemu-kvm

### CODE REVIEW

**Comment by anarcat** [comment]
this LGTM. i made a similar tweak in #60, for Debian. the root case is, of course, the same. i did not drop older releases however, as those are still somewhat supported on the debian side and I didn't want to have too many things in my first PR here. :)

i do wonder if we should make the package name conditional on the architecture though. presumably it would be possible for someone to use this module on some ARM machine, and this setup would break in the sense that it wouldn't be able to leverage KVM to accelerate the virtualization and indeed, it would be pure emulation, and therefore slow as heck...

but i haven't figured out how to do the magic trick in hiera to turn `x86_64` (the `os.hardware` fact) into `x86`  which is what we'd need here... or maybe we could have a `os-release-arch` hierarchy?

**Comment by trefzer** [comment]
I just added a additional architecture specific layer (and moved the os specific data into subdirectories). Could you please adapt the merge request into the new directory structure.

I also would like you do not change the defaults in Ubuntu.yaml. Since these are also used for eg. 19.x systems. yes they are not supported systems but I expect there are some users anyway.

Could you check if python-libvirt package is still available in Ubuntu version X ? if not you can switch to python3-libvirt package.

Thanks a lot.

**Comment by anarcat** [comment]
> I also would like you do not change the defaults in Ubuntu.yaml. Since these are also used for eg. 19.x systems. yes they are not supported systems but I expect there are some users anyway.

for what it's worth, on Debian's side of things, the only release missing from the list is Debian 7 and earlier, and it *really* doesn't make sense to support those, in my opnion, since it's been out of support since 2016 (2018 if you count LTS)... but maybe it makes more sense for ubuntu's fast-paced release cycles, which are much more likely to snarl people in an unsupported release...

**Comment by trefzer** [comment]
I rebased youre commits and adapted the python 3 usage for migration and merged into master branch.
Please reopen if I did a mistake.
Thanks for the contribution.

**Comment by raoulbhatia** [comment]
Thanks @trefzer for picking this up.  I'll check the newest changes in my branch and will report in case of any issues.

Cheers 🇨🇭

**Pull request closed without merging**
