### PR TITLE
vaious fixes for Debian bullseye

### PR DESCRIPTION
**Pull request by anarcat**
This is similar to #59 in the sense that the newer Debian
release *also* doesn't have a qemu-kvm package, which is now a "meta
package". This matters because as things stand, this module will
constantly be effecting changes on servers, like this:

    Notice: /Stage[main]/Libvirt::Install/Package[qemu-kvm]/ensure: created (corrective)

Instead of creating a one-shot solution, we create data files for the
older release which will, eventually, go away.

One downside of this new package name is that it hardcodes the
architecture. Unfortunately, the package name doesn't match the
architecture provided by facts:

    anarcat@curie:libvirt$ facter -p | grep x86
      hardware => "x86_64",
      platform => "x86_64-linux-gnu",

... so it seems unlikely this can be fixed purely with Hiera logic.

### CODE REVIEW

**Comment by trefzer** [comment]
good point. 
I just made a merge request for an architecture specific layer so we can solve this.
I also move the version specific files to a separate directory.
Could you rebase your merge request for the new data directory structure ?
Additionaly: 

- python-libvirt is not available anymore in bullseye you should change this to python3-libvirt
- I would like if you do not change the Debian.yaml file, but add add a Debian-11.yaml (I know the default will be outdated, but like this we ensure not to break any old systems (eg Debian 7 ;)).

thanks !

**Comment by anarcat** [comment]
before I go any further...

> I would like if you do not change the Debian.yaml file, but add add a Debian-11.yaml (I know the default will be outdated, but like this we ensure not to break any old systems (eg Debian 7 ;)).

i understand where you're coming from, but Debian 7 is largely unsupported, both by this module but also by the entire Debian community. It's oldoldoldoldstable, if i count this right: it's two LTS back. So I don't understand why we'd want to make provisions for that old stuff.

And mind you, i'm the one who's running Debian packages for puppet and constantly struggles with that because i'm stuck in Puppet 5 land (see [this page for our progress on puppet 7, btw](https://wiki.debian.org/Teams/Puppet/Work)), so i don't take such issues lightly.

My argument with this is that it's *much* better to automatically support *future* releases (since that will not require any changes in the future) rather than try to permanently support *past* releases. We don't even know if those specs actually work in Debian 7 anyways (i bet they don't), why should we bother?

**Comment by anarcat** [comment]
hmm... now i see that you coupled the architecture-specific stuff with the version number, so I guess there's no way around having the version number in from bullseye on.

i do think that's a waste of time: if nothing changes on Debian's side, you'll still have to create a new YAML file (and possibly *multiple*) for each new release going forward. with my suggested approach, at least you converge towards having a single YAML file (or one per architecture) assuming things eventually stabilize on Debian's side.

anyways, i'll follow your change, but i encourage you to reconsider. i think the proper hiera.yaml would be:

```
  - name: 'architecture specific'
    path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
```

we could even have *both* if we need to...

**Comment by anarcat** [comment]
i have made the requested changes:

 1. i rebased on top of the arch-specific patch
 2. i moved the default back to "whatever is before current stable"
 3. i moved the bullseye config to 12_amd64.yaml

I haven't made configurations for other architectures for now, but that should be fairly easy to implement.

**Comment by trefzer** [comment]
thanks for the fast changes ;) I will check and merge.
I had to make the architecture version specific, because otherwise a architecture specific entry would also have been taken for older versions (and overwrite defaults) (yes I know we could overwrite that ...). But I prefer this solution being more obvious in future.
Yes I know Debian 7 is old ;) I prefer to overwrite defaults for newer versions and not change the old defaults for all. I agree for Debian your solution would have been easier to maintain but like this we have the same for all distributions.

**Comment by trefzer** [comment]
So thanks alot for your work. I just did some more cosmetics (and split architecture from non architecture specific), give some more files but makes it clearer I think ;).

And btw. thanks for your Debian puppet work (I just read the wiki page I did not know yet).

**Comment by anarcat** [comment]
> So thanks alot for your work. I just did some more cosmetics (and split architecture from non architecture specific), give some more files but makes it clearer I think ;).

oh yeah that makes a lot of sense.

> And btw. thanks for your Debian puppet work (I just read the wiki page I did not know yet).

that warms my heart, many thanks, and thank you for this module, keep up the good work! :)

**Comment by anarcat** [comment]
so here's another case where this doesn't work: i'm trying to deploy this module in Debian testing, and that doesn't have a "real" "major" version number (e.g. `12`) and instead the codename (`bookworm/sid`) which, obviously, is .. not great. but it's the way things are right now. this means it's basically impossible, even in a fork, to have settings for testing, which is... not great.

could we revisit this idea? :)

**Comment by trefzer** [comment]
hm. I have no idea what %{facts.os.release.major} for bookworm or sid is. Can you enlight me ?

So your suggestion is either (version 1):
```
- name: 'Major Version architecture specific'
  path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
- name: 'Major Version'
  path: '%{facts.os.name}/%{facts.os.release.major}.yaml'
```
or (version 2)
```
- name: 'Major Version'
  path: '%{facts.os.name}/%{facts.os.release.major}.yaml'
- name: 'Major Version architecture specific'
  path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
```
In version 1 we have no simple possibility to support the older Debian versions, because the architecture dependent version 
is always taken before the release (or default.yaml) version.

In version 2 we will be in troubles the next time the architecture dependent package will be renamed (and the package stays architecture dependent).

Both is a nogo for me. I see currently no solution to this dilemma beside having the combined release/architecture version I implemented. Since many modules use %{facts.os.release.major} you have this problem with other modules too !
So you probably need to overwrite the setting in your environment specific hierarchy (like for other modules).

Well and for the default.yaml file. If we make it to always support the most recent version we each time risk to break an older version (so each time we have to check all old version to include the old value) if a change is needed. So there is less risk to break a older version if we overwrite with a release specific version (this also means less work for review !).
I agree to cleanup supported versions (removing old versions, moving to defaults) from time to time but this is something that should be done increasing the major module version number (which I plan to do soon when my work on removing all the exec statements will success ....).

I think bookworm should already specify 13 for facts.os.release.major. If not it's probably a debian bug. No idea what sid reports (99 ?). So if bookworm reports 13 we could add a 13[|_amd64].yaml file easily (as soon as we think the settings will not change to much anymore). If sid reports 99, we could do that as well with a explanation/comment in the yaml file.   

So lot of text, but I still think the choosen version is best. 

Cheers 
Benedikt

**Pull request merged**
