### PR TITLE
Fix "Could not prefetch libvirt_pool provider 'virsh'

### LINKED ISSUE #34: Could not prefetch libvirt_pool provider 'virsh'
One of the [recent changes](https://github.com/cirrax/puppet-libvirt/commit/c8b92633297c3f88f2a3ba8f3773988b64f0b912#diff-abd533138d61d01cea6b621b505c3f2cR37) broke the virsh provider:
```
Error: Could not prefetch libvirt_pool provider 'virsh': undefined local variable or method `provider' for Puppet::Type::Libvirt_pool::ProviderVirsh:Class
Error: Failed to apply catalog: undefined local variable or method `provider' for Puppet::Type::Libvirt_pool::ProviderVirsh:Class
```

### PR DESCRIPTION
**Pull request by onyxmaster**
Fixes #34

### CODE REVIEW

**Comment by trefzer** [comment]
uups !
Thanks for this fix. I will merge an release a new version as soon as test are finished without error.

**Comment by onyxmaster** [comment]
The CI job [failed with timeout](https://travis-ci.org/cirrax/puppet-libvirt/jobs/583721396#L2978), I don't think that proposed changes are the cause of this. I see that the previous build [failed too for the same reason](https://travis-ci.org/cirrax/puppet-libvirt/jobs/575785201#L2979). Maybe the tests themselves are doing something so slow that Travis doesn't like it?

**Comment by onyxmaster** [comment]
It seems that [enabling coverage report](https://github.com/cirrax/puppet-libvirt/commit/175ed3df9927e19b0ff367e2e3b72aff0c0dd546) leads to this slowness.

**Comment by trefzer** [comment]
yepp your'e right. something for todo !

So anyway, thanks alot for the fix.

**Pull request merged**
