### PR TITLE
Make defaults from Ubuntu 18.04 new global Ubuntu defaults

### PR DESCRIPTION
**Pull request by raoulbhatia**
```
git mv Ubuntu.yaml Ubuntu-16.04.yaml
git mv Ubuntu-18.04.yaml Ubuntu.yaml
```

### CODE REVIEW

**Comment by trefzer** [comment]
Hi
Thanks for you're request. I basically agree, but 2 things:
First, according to metadata.json, we support:
 {
      "operatingsystem": "Ubuntu",
      "operatingsystemrelease": [
        "14.04",
        "16.04",
        "17.10",
        "18.04"
      ]
    },
So we should duplicate the original config also to the other older versions.

Second, why do you delete libvirt::qemu_hook_packages in the default ubuntu.yaml ?

**Comment by raoulbhatia** [comment]
Thanks for the review.

Ad 1. Supported Releases: I pushed additional commits that I hope will cover this: 0e1ff5e and 188ed31

Ad 2. libvirt::qemu_hook_packages: I was creating my fix in a rush.  I pushed 3f1cef4 to fix this.

Please let me know if this PR looks better now.

Cheers,
Raoul

**Comment by raoulbhatia** [comment]
@trefzer please let me know if you'd like to see any further changes.

**Comment by trefzer** [comment]
there was only a minor comment I changed. 
Thanks for the contribution. 
The patches are now merged and available in version 3.4.0.

**Comment by raoulbhatia** [comment]
Thanks 🇨🇭 

For the records, fixed via a2cfd64118658c59ebb680e7a609bc19d4c03359

**Pull request closed without merging**
